apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.net_attachment_definition }}
  labels:
    vnf-name: {{ .Values.vnf_name }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
spec:
  config: |
    {
        "cniVersion": "0.3.1",
        "name": "ovn4nfv-k8s-plugin",
        "type": "ovn4nfvk8s-cni"
    }
